rootProject.name = "tinn"
include("tinn-api")
include("tinn-math")
include("tinn-color")
include("tinn-opengl")
include("tinn-nodes")
include("tinn-ui")
include("tinn-core")
include("tinn-studio")
include("tinn-serialization")